### ISSUE TITLE
Interface is nil

### ISSUE THREAD

**Issue by JoaoAndreSa** [lca1/unlynx#11]
Sometimes and (randomly) I get an `interface is nil` error which I cannot replicate locally. Should try to get more information about it and fix it..

**Comment by ineiti** [comment]
Does it happen in Travis? Or only on your local computer?

You can also run the tests with

`go test -race`

which might show where there is a race and help you find the error.

**Comment by JoaoAndreSa** [comment]
I have yet to get this error locally. I get it in Travis sometimes (but very very rarely).
Both locally and in Travis I test unlynx with the `-race` flag activated. 

In Makefile:
`test_local:
	go test -v -race -short -p=1 ./...`

**Comment by JoaoAndreSa** [comment]
Just looked in travis for it and found it [https://travis-ci.org/lca1/unlynx]( https://travis-ci.org/lca1/unlynx)

<img width="971" alt="Screenshot 2019-03-27 at 10 52 25" src="https://user-images.githubusercontent.com/9702328/55066626-7f19a800-507e-11e9-8123-ca3bf041c2cf.png">

**Comment by ineiti** [comment]
OK - the link is stale. You can click on the line-number next to the error, and post this one. I think it's a bit longer-living that way.

I added a PR here: #12 - please merge it, and then try again. If you don't get an error, and only a failure, I'll create a PR to better wrap the `Survey.Get` and `Survey.Put`, so that we can if the `Put` is never called, or if the `Put` stores a `nil` value.

**Comment by ineiti** [comment]
And it's already failing ;)

https://travis-ci.org/lca1/unlynx/builds/512423154#L1983

**Comment by JoaoAndreSa** [comment]
Yes it's always in this default_test.TestAllServersNoDPs(). I am still trying to figure out why this happens

**Comment by JoaoAndreSa** [comment]
#14 will fix this issue (in an ugly way)
